### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by donotdespair** [donotdespair/bsvarTVPs#5]
- [x] impulse response *computations*
- [x] assign **classes** for Bayesian model estimation output
- [x] impulse response `plot`
- [x] conditional variance `compute` and `plot`
- [x] state probabilities `compute` and `plot`
- [x] `compute_S5_component_density`
- [x] plots for `component` probabilities
- [x] `drop_sv` and `drag_sv` functions to simplify the estimation output
- [x] functions to `thin_MCMC` and split to with and without SV estimates
- [x] HERE: `B` matrix draws normalisation via `normalise` method
- [x] HERE: develop `normalise.` functions for separate classes
