### ISSUE TITLE
Implement models with 3-level local global hierarchical priors for `B` and `A`

### ISSUE THREAD

**Issue by donotdespair** [donotdespair/bsvarTVPs#6]
### for `B` matrix
$$ 
B_n | \gamma_{Bn} \sim\mathcal{N}_{r_n}(0, \gamma _{Bn} I _{r_n}) 
$$

$$
\gamma _{Bn} | \underline{s} _{Bn} \sim\mathcal{IG}2 (\underline{s} _{Bn}, \underline{\nu} _{B})
$$

$$
\underline{s} _{Bn} | \underline{s} _{B} \sim\mathcal{G} (\underline{s} _{B}, \underline{a} _{B})
$$

$$
\underline{s} _{B} \sim\mathcal{IG}2 (\underline{s} _{BB}, \underline{\nu} _{BB} )
$$

### for `A` matrix
$$ 
A_n | \gamma_{An} \sim\mathcal{N}_{K}(\underline{A} _n, \gamma _{An} I _{K}) 
$$

$$
\gamma _{An} | \underline{s} _{An} \sim\mathcal{IG}2 (\underline{s} _{An}, \underline{\nu} _{A})
$$

$$
\underline{s} _{An} | \underline{s} _{A} \sim\mathcal{G} (\underline{s} _{A}, \underline{a} _{A})
$$

$$
\underline{s} _{A} \sim\mathcal{IG}2 (\underline{s} _{AA}, \underline{\nu} _{AA} )
$$

## TO-DO LIST

- [x] rename the functions and classes from `S5` to `TVI`
- [x] TVI-SVAR-SV
- [x] MS-SVAR-SV
- [x] MS-TVI-SVAR-SV

## consider also hommoskedastic models

- [x] TVI-SVAR
- [x] MS-SVAR
- [x] MS-TVI-SVAR
