### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by donotdespair** [donotdespair/bsvarTVPs#8]
- [ ] expand the existing methods to accommodate new models of class `PosteriorBSVARMSTVI`, `PosteriorBSVARMS`, and `PosteriorBSVARTVI`
- [ ] prepare `specify_` classes
- [ ] prepare new methods compatible with **bsvars**
- [ ] develop unit tests
- [ ] develop documentation including examples
